// <auto-generated />
using System;
using MedicalCabinetAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalCabinetAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413135130_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoctorSpeciality", b =>
                {
                    b.Property<int>("DoctorIdUser")
                        .HasColumnType("int");

                    b.Property<int>("SpecialitiesIdS")
                        .HasColumnType("int");

                    b.HasKey("DoctorIdUser", "SpecialitiesIdS");

                    b.HasIndex("SpecialitiesIdS");

                    b.ToTable("DoctorSpeciality");
                });

            modelBuilder.Entity("MedicalCabinetAPI.Models.Allergy", b =>
                {
                    b.Property<int>("IdAllergy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAllergy"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCabinet")
                        .HasColumnType("int");

                    b.Property<int>("IdPatient")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleFR")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAllergy");

                    b.HasIndex("IdPatient");

                    b.ToTable("Allergies");
                });

            modelBuilder.Entity("MedicalCabinetAPI.Models.Consultation", b =>
                {
                    b.Property<int>("IdCons")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCons"));

                    b.Property<float>("BloodMesure")
                        .HasColumnType("real");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilesConsultation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("HeartMesure")
                        .HasColumnType("real");

                    b.Property<int>("HeightMesure")
                        .HasColumnType("int");

                    b.Property<int>("IdCabinet")
                        .HasColumnType("int");

                    b.Property<int>("IdDoctorCons")
                        .HasColumnType("int");

                    b.Property<int>("IdInsurancePatient")
                        .HasColumnType("int");

                    b.Property<int>("IdPatient")
                        .HasColumnType("int");

                    b.Property<string>("Observation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OxygeneMesure")
                        .HasColumnType("int");

                    b.Property<int>("Payed")
                        .HasColumnType("int");

                    b.Property<float>("SizeMesure")
                        .HasColumnType("real");

                    b.HasKey("IdCons");

                    b.HasIndex("IdDoctorCons");

                    b.HasIndex("IdPatient");

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("MedicalCabinetAPI.Models.Disease", b =>
                {
                    b.Property<int>("IdDisease")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDisease"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<string>("Files")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDC")
                        .HasColumnType("int");

                    b.Property<int>("IdMedicineSpeciality")
                        .HasColumnType("int");

                    b.Property<string>("IdTreatmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicationList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SymptomList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleFR")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDisease");

                    b.HasIndex("IdDC");

                    b.ToTable("Diseases");
                });

            modelBuilder.Entity("MedicalCabinetAPI.Models.DiseaseCategory", b =>
                {
                    b.Property<int>("IdDC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDC"));

                    b.Property<string>("DescDC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleDCAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleDCEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleDCFR")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDC");

                    b.ToTable("DiseaseCategories");
                });

            modelBuilder.Entity("MedicalCabinetAPI.Models.FamilyRelations", b =>
                {
                    b.Property<int>("IdFamily")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFamily"));

                    b.Property<int>("IdPatient")
                        .HasColumnType("int");

                    b.Property<int>("IdPatient2")
                        .HasColumnType("int");

                    b.Property<int>("IsCousin")
                        .HasColumnType("int");

                    b.Property<int>("IsFather")
                        .HasColumnType("int");

                    b.Property<int>("IsHusband")
                        .HasColumnType("int");

                    b.Property<int>("IsMother")
                        .HasColumnType("int");

                    b.Property<int>("IsSister")
                        .HasColumnType("int");

                    b.Property<int>("IsSun")
                        .HasColumnType("int");

                    b.Property<int>("IsWife")
                        .HasColumnType("int");

                    b.HasKey("IdFamily");

                    b.HasIndex("IdPatient");

                    b.ToTable("FamilyRelations");
                });

            modelBuilder.Entity("MedicalCabinetAPI.Models.Insurance", b =>
                {
                    b.Property<int>("IdInsurance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInsurance"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<string>("AddressCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCabinet")
                        .HasColumnType("int");

                    b.Property<int>("IdPatient")
                        .HasColumnType("int");

                    b.Property<string>("PhoneCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdInsurance");

                    b.HasIndex("IdPatient");

                    b.ToTable("Insurances");
                });

            modelBuilder.Entity("MedicalCabinetAPI.Models.MedicalFolder", b =>
                {
                    b.Property<int>("IdMF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMF"));

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BleedingDisorder")
                        .HasColumnType("int");

                    b.Property<string>("BloodType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Diabete")
                        .HasColumnType("int");

                    b.Property<string>("Files")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Height")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HighBloodPressure")
                        .HasColumnType("int");

                    b.Property<int>("HighCholesterol")
                        .HasColumnType("int");

                    b.Property<int>("HowManyChildren")
                        .HasColumnType("int");

                    b.Property<int>("IdCabinet")
                        .HasColumnType("int");

                    b.Property<int>("IdPatient")
                        .HasColumnType("int");

                    b.Property<int>("IdPatientNumber")
                        .HasColumnType("int");

                    b.Property<string>("IsMarried")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SurgeryBefore")
                        .HasColumnType("int");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhenMarried")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMF");

                    b.HasIndex("IdPatient")
                        .IsUnique();

                    b.ToTable("MedicalFolders");
                });

            modelBuilder.Entity("MedicalCabinetAPI.Models.Prescription", b =>
                {
                    b.Property<int>("IdP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdP"));

                    b.Property<int>("IdCabinet")
                        .HasColumnType("int");

                    b.Property<int>("IdConsultation")
                        .HasColumnType("int");

                    b.Property<int>("IdPatient")
                        .HasColumnType("int");

                    b.Property<string>("MedicationsTitleDaysPerDays")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrescriptionText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdP");

                    b.HasIndex("IdConsultation");

                    b.HasIndex("IdPatient");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("MedicalCabinetAPI.Models.Speciality", b =>
                {
                    b.Property<int>("IdS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdS"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleFR")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdS");

                    b.ToTable("Specialities");
                });

            modelBuilder.Entity("MedicalCabinetAPI.Models.Symptom", b =>
                {
                    b.Property<int>("IdSymptom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSymptom"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCabinet")
                        .HasColumnType("int");

                    b.Property<int>("IdPatient")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleFR")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSymptom");

                    b.HasIndex("IdPatient");

                    b.ToTable("Symptoms");
                });

            modelBuilder.Entity("MedicalCabinetAPI.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCity")
                        .HasColumnType("int");

                    b.Property<int>("IdCountry")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("Phone2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MedicalCabinetAPI.Models.Doctor", b =>
                {
                    b.HasBaseType("MedicalCabinetAPI.Models.User");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCabinet")
                        .HasColumnType("int");

                    b.Property<int>("IdDoctor")
                        .HasColumnType("int");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Users", null, t =>
                        {
                            t.Property("HireDate")
                                .HasColumnName("Doctor_HireDate");

                            t.Property("IdCabinet")
                                .HasColumnName("Doctor_IdCabinet");
                        });

                    b.HasDiscriminator().HasValue("Doctor");
                });

            modelBuilder.Entity("MedicalCabinetAPI.Models.MedicalAssistant", b =>
                {
                    b.HasBaseType("MedicalCabinetAPI.Models.User");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAssistant")
                        .HasColumnType("int");

                    b.Property<int>("IdCabinet")
                        .HasColumnType("int");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Users", null, t =>
                        {
                            t.Property("IdCabinet")
                                .HasColumnName("MedicalAssistant_IdCabinet");
                        });

                    b.HasDiscriminator().HasValue("MedicalAssistant");
                });

            modelBuilder.Entity("MedicalCabinetAPI.Models.Patient", b =>
                {
                    b.HasBaseType("MedicalCabinetAPI.Models.User");

                    b.Property<string>("DateInscription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCabinet")
                        .HasColumnType("int");

                    b.Property<int>("IdPatient")
                        .HasColumnType("int");

                    b.Property<string>("IllnessCardCopie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IllnessCardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IllnessFinDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsuranceCopie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsuranceFinDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsuranceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientNumber")
                        .HasColumnType("int");

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator().HasValue("Patient");
                });

            modelBuilder.Entity("DoctorSpeciality", b =>
                {
                    b.HasOne("MedicalCabinetAPI.Models.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorIdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalCabinetAPI.Models.Speciality", null)
                        .WithMany()
                        .HasForeignKey("SpecialitiesIdS")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicalCabinetAPI.Models.Allergy", b =>
                {
                    b.HasOne("MedicalCabinetAPI.Models.Patient", null)
                        .WithMany()
                        .HasForeignKey("IdPatient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicalCabinetAPI.Models.Consultation", b =>
                {
                    b.HasOne("MedicalCabinetAPI.Models.Doctor", null)
                        .WithMany("Consultations")
                        .HasForeignKey("IdDoctorCons")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MedicalCabinetAPI.Models.Patient", null)
                        .WithMany("Consultations")
                        .HasForeignKey("IdPatient")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicalCabinetAPI.Models.Disease", b =>
                {
                    b.HasOne("MedicalCabinetAPI.Models.DiseaseCategory", null)
                        .WithMany()
                        .HasForeignKey("IdDC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicalCabinetAPI.Models.FamilyRelations", b =>
                {
                    b.HasOne("MedicalCabinetAPI.Models.Patient", null)
                        .WithMany("FamilyRelations")
                        .HasForeignKey("IdPatient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicalCabinetAPI.Models.Insurance", b =>
                {
                    b.HasOne("MedicalCabinetAPI.Models.Patient", null)
                        .WithMany()
                        .HasForeignKey("IdPatient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicalCabinetAPI.Models.MedicalFolder", b =>
                {
                    b.HasOne("MedicalCabinetAPI.Models.Patient", null)
                        .WithOne("MedicalFolder")
                        .HasForeignKey("MedicalCabinetAPI.Models.MedicalFolder", "IdPatient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicalCabinetAPI.Models.Prescription", b =>
                {
                    b.HasOne("MedicalCabinetAPI.Models.Consultation", null)
                        .WithMany()
                        .HasForeignKey("IdConsultation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalCabinetAPI.Models.Patient", null)
                        .WithMany("Prescriptions")
                        .HasForeignKey("IdPatient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicalCabinetAPI.Models.Symptom", b =>
                {
                    b.HasOne("MedicalCabinetAPI.Models.Patient", null)
                        .WithMany()
                        .HasForeignKey("IdPatient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicalCabinetAPI.Models.Doctor", b =>
                {
                    b.Navigation("Consultations");
                });

            modelBuilder.Entity("MedicalCabinetAPI.Models.Patient", b =>
                {
                    b.Navigation("Consultations");

                    b.Navigation("FamilyRelations");

                    b.Navigation("MedicalFolder");

                    b.Navigation("Prescriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
